name: npm-release

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    uses: ./.github/workflows/release.yml
    with:
      npm: true
    # Configure the repository's NPM_TOKEN secret with permission to publish the npm packages.
    secrets: inherit
